# Generated by Django 3.1.7 on 2021-05-07 04:10

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, validators=[core.models.validate_reminder_length], verbose_name=' remind me to..')),
                ('date', models.DateTimeField(verbose_name=' set time alarm')),
                ('repeat', models.CharField(choices=[('0', 'no repeat'), ('600', '10 minutes'), ('900', '15 minutes'), ('1800', '30 minutes'), ('3600', '1 hour'), ('10800', '3 hours'), ('21600', '6 hours'), ('86400', '1 day'), ('259200', '3 days'), ('604800', '7 days')], default='default', max_length=10, verbose_name=' repeat interval')),
                ('active', models.BooleanField(default=True, verbose_name=' active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
